import './globals.css';
import Navbar from './components/Navbar/index';
import Footer from './components/Footer/Footer';
import React from 'react';


export const metadata = {
  title: 'Courses',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (

    <html lang="en">
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap" rel="stylesheet" />
      </head>
      <body>
              <Navbar />
              {children}
              <Footer />
    </body>
    </html >
  )
}
